apiVersion: v1
kind: Service
metadata:
  name: ski-server-service
spec:
  selector:
    app: ski-server   # Label selector matching the Deployment Pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
